// flow-typed signature: 1ebe0f1e54091109f190b9ef709ed709
// flow-typed version: <<STUB>>/babel-plugin-react-css-modules_v5.2.4/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-css-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-css-modules/benchmark/test' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/attributeNameExists' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/browser/getClassName' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/browser/schemas/optionsDefaults' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/conditionalClassMerge' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/createObjectExpression' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/createSpreadMapper' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/getClassName' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/handleSpreadClassName' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/replaceJsxExpressionContainer' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/requireCssModule' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/resolveStringLiteral' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/schemas/optionsDefaults' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-css-modules/dist/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-css-modules/benchmark/test.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/benchmark/test'>;
}
declare module 'babel-plugin-react-css-modules/demo/webpack.config.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/demo/webpack.config'>;
}
declare module 'babel-plugin-react-css-modules/dist/attributeNameExists.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/attributeNameExists'>;
}
declare module 'babel-plugin-react-css-modules/dist/browser/getClassName.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/browser/getClassName'>;
}
declare module 'babel-plugin-react-css-modules/dist/browser/schemas/optionsDefaults.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/browser/schemas/optionsDefaults'>;
}
declare module 'babel-plugin-react-css-modules/dist/conditionalClassMerge.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/conditionalClassMerge'>;
}
declare module 'babel-plugin-react-css-modules/dist/createObjectExpression.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/createObjectExpression'>;
}
declare module 'babel-plugin-react-css-modules/dist/createSpreadMapper.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/createSpreadMapper'>;
}
declare module 'babel-plugin-react-css-modules/dist/getClassName.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/getClassName'>;
}
declare module 'babel-plugin-react-css-modules/dist/handleSpreadClassName.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/handleSpreadClassName'>;
}
declare module 'babel-plugin-react-css-modules/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/index'>;
}
declare module 'babel-plugin-react-css-modules/dist/replaceJsxExpressionContainer.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/replaceJsxExpressionContainer'>;
}
declare module 'babel-plugin-react-css-modules/dist/requireCssModule.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/requireCssModule'>;
}
declare module 'babel-plugin-react-css-modules/dist/resolveStringLiteral.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/resolveStringLiteral'>;
}
declare module 'babel-plugin-react-css-modules/dist/schemas/optionsDefaults.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/schemas/optionsDefaults'>;
}
declare module 'babel-plugin-react-css-modules/dist/types.js' {
  declare module.exports: $Exports<'babel-plugin-react-css-modules/dist/types'>;
}
