// flow-typed signature: 78f137b2d1bca5c45fcf77a30392dd9f
// flow-typed version: <<STUB>>/incstr_v1.2.3/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'incstr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'incstr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'incstr/incstr' {
  declare module.exports: any;
}

declare module 'incstr/test/benchmark' {
  declare module.exports: any;
}

declare module 'incstr/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'incstr/incstr.js' {
  declare module.exports: $Exports<'incstr/incstr'>;
}
declare module 'incstr/test/benchmark.js' {
  declare module.exports: $Exports<'incstr/test/benchmark'>;
}
declare module 'incstr/test/test.js' {
  declare module.exports: $Exports<'incstr/test/test'>;
}
