// flow-typed signature: 7e22738e44670f73ecfac9e2166ddf86
// flow-typed version: <<STUB>>/koa-generic-session_v2.0.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-generic-session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-generic-session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-generic-session/lib/memory_store' {
  declare module.exports: any;
}

declare module 'koa-generic-session/lib/session' {
  declare module.exports: any;
}

declare module 'koa-generic-session/lib/store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-generic-session/lib/memory_store.js' {
  declare module.exports: $Exports<'koa-generic-session/lib/memory_store'>;
}
declare module 'koa-generic-session/lib/session.js' {
  declare module.exports: $Exports<'koa-generic-session/lib/session'>;
}
declare module 'koa-generic-session/lib/store.js' {
  declare module.exports: $Exports<'koa-generic-session/lib/store'>;
}
