// flow-typed signature: 5b7b01bccd9995cdd2211efce65992f5
// flow-typed version: <<STUB>>/koa-redis_v3.1.3/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-redis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-redis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-redis/index' {
  declare module.exports: $Exports<'koa-redis'>;
}
declare module 'koa-redis/index.js' {
  declare module.exports: $Exports<'koa-redis'>;
}
