// flow-typed signature: 9914125681122cfdad52f0f395f8eac9
// flow-typed version: <<STUB>>/react-icon-base_v2.1.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-icon-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-icon-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-icon-base/es/index' {
  declare module.exports: any;
}

declare module 'react-icon-base/lib/index' {
  declare module.exports: any;
}

declare module 'react-icon-base/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-icon-base/es/index.js' {
  declare module.exports: $Exports<'react-icon-base/es/index'>;
}
declare module 'react-icon-base/index' {
  declare module.exports: $Exports<'react-icon-base'>;
}
declare module 'react-icon-base/index.js' {
  declare module.exports: $Exports<'react-icon-base'>;
}
declare module 'react-icon-base/lib/index.js' {
  declare module.exports: $Exports<'react-icon-base/lib/index'>;
}
declare module 'react-icon-base/test/index.test.js' {
  declare module.exports: $Exports<'react-icon-base/test/index.test'>;
}
