// flow-typed signature: 3c60a65f9d1008d5f4ebc8e11dd7e33c
// flow-typed version: <<STUB>>/@paralect/common-logger_v0.1.10/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paralect/common-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paralect/common-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paralect/common-logger/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paralect/common-logger/src/index.js' {
  declare module.exports: $Exports<'@paralect/common-logger/src/index'>;
}
