// flow-typed signature: ee7d6971417a2c4d4c0e6f96e28869f3
// flow-typed version: <<STUB>>/@paralect/eslint-config_v1.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paralect/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paralect/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@paralect/eslint-config/index' {
  declare module.exports: $Exports<'@paralect/eslint-config'>;
}
declare module '@paralect/eslint-config/index.js' {
  declare module.exports: $Exports<'@paralect/eslint-config'>;
}
